# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f693191b48d973b9bbc6eca26bda5a0190ac295ac42c04e41426d2c5337b79f35d54bf007b17af5e42e1bc778d165e1d45c23b1b54c160e3d27c8e789818905d

test:
  secret_key_base: 5419c895a3b225beec9123ec636d372cac4bb0dc1a1cb552915330acffb208257196a603e4d589dc5efd88c2b6f884b68280cab3cf5b342d2a25b2906074c2e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
